language: python

python:
    - "3.6"

env:
    global:
    # Doctr deploy key for dask/dask-tutorial
    - secure: ""

before_install:
    - sudo apt-get update
    - sudo apt-get install graphviz

install:
    # Install conda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda

    # Install dependencies
    - conda env create -n test -f binder/environment.yml
    - source activate test

    # Install testing dependencies
    - conda install pathlib nbconvert nbformat jupyter_client ipykernel

    # Install documentation dependencies
    - pip install nbsphinx dask-sphinx-theme

script:
    - set -e
    - source activate test
    - sphinx-build -M html . _build -vv
    - pip install doctr
    - doctr deploy --built-docs _build/html .

notifications:
  email: false
