name: dask-tutorial
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - numpy
  - h5py
  - scipy
  - toolz
  - bokeh
  - dask
  - distributed
  - notebook
  - matplotlib
  - Pillow
  - pandas
  - pandas-datareader
  - pytables
  - scikit-learn
  - snakeviz
  - ujson
  - graphviz
  - pip
  - s3fs
  - fastparquet
  - pip:
    - graphviz 
    - cachey
