name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - nodejs
  # TODO: Bump jupyterlab to 2.x once extensions have been made compatibility updates
  - jupyterlab=1.*
  - numpy>=1.18.1
  - h5py
  - scipy>=1.3.0
  - toolz
  - bokeh>=2.0.0
  - dask=2.11.0
  # TODO: Bump dask-labextension to >=2 once extensions have been made compatibility updates
  - dask-labextension=1.1.0
  - distributed=2.11.0
  - notebook
  - matplotlib
  - Pillow
  - pandas>=1.0.1
  - pandas-datareader
  - pytables
  - scikit-learn>=0.22.1
  - scikit-image>=0.15.0
  - snakeviz
  - ujson
  - pip
  - s3fs
  - fastparquet
  - dask-ml
  - ipywidgets>=7.5
  - cachey
  - python-graphviz
  - zarr
