name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab=3
  - numpy=1.23
  - scipy=1.8
  - bokeh=2.4
  - dask=2022.6.1
  - dask-labextension
  - distributed=2022.6.1
  - matplotlib
  - pandas=1.4
  - pip
  - python-graphviz
  - pyarrow
  - ipycytoscape
  - pyarrow
  - s3fs
  - zarr
  - pooch
  - xarray
  - mamba
