name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - nodejs
  - numpy=1.16.4
  - h5py
  - scipy=1.3.0
  - toolz
  - bokeh=1.2.0
  - dask=1.2.2
  - distributed=1.28.1
  - notebook
  - matplotlib
  - Pillow
  - pandas=0.24.2
  - pandas-datareader
  - pytables
  - scikit-learn=0.21.1
  - scikit-image=0.15.0
  - snakeviz
  - ujson
  - pip
  - s3fs=0.2.1
  - fastparquet=0.3.0
  - dask-ml=0.12.0
  - ipywidgets=7.4.2
  - cachey
  - python-graphviz
